# .github/workflows/ci.yml

# Continuous Integration (CI) Workflow
name: Lint and Run Unit Tests

# This workflow will run unit tests whenever we push commits to the `main`
# branch, or whenever there's a pull request to the `main` branch
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomlkit
          pip install python-frontmatter
          pip install pycodestyle
          pip install autopep8
          pip install pylint
          pip install pytest
          pip install coverage

      - name: Test with pytest
        run: |
          pytest

      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=9.0 src/ tests/ conftest.py
